import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Fondamento, Geist_Mono, Luckiest_Guy, Sniglet } from "next/font/google";


const luckiestGuy = Luckiest_Guy({
  variable: "--font-luckiest-guy",
  weight: "400", // Only "400" is available for Luckiest Guy
  subsets: ["latin"],
});

const SnigletMono = Sniglet({
  variable: "--font-snig",
  subsets: ["latin"],
  weight: ["400", "800"],
});

const FondamentoMono = Fondamento({
  variable: "--font-fondamento",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body
        className={`${luckiestGuy.variable} ${SnigletMono.variable}  ${FondamentoMono.variable} antialiased`}
      >
        <Toaster position="top-right"/>
        {children}
      </body>
    </html>
  );
}
